//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int Id { get; set; }
        public int ComponentId { get; set; }
        public string AspNetUserId { get; set; }

        [RegularExpression(@"^.{3,}$", ErrorMessage = "Minimum 3 characters required")]
        [Required(ErrorMessage = "Required")]
        [StringLength(1000, MinimumLength = 3, ErrorMessage = "Maximum 1000 characters")]
        public string Message { get; set; }


        public System.DateTime TimeStamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Component Component { get; set; }
        public string AspNetUserName { get; internal set; }
    }
}
