//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComponentStuff : DbContext
    {
        public ComponentStuff()
            : base("name=ComponentStuff")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<ComponentImage> ComponentImages { get; set; }
        public virtual DbSet<ComponentListEntry> ComponentListEntries { get; set; }
        public virtual DbSet<ComponentList> ComponentLists { get; set; }
        public virtual DbSet<Component> Components { get; set; }
    }
}
